version: '3.7'

services:
  flask-app:
    image: flask-app
    ports:
      - 5000:5000
    volumes:
      - ./Interface-web/app_code/.:/app
      
  api-app:
    image: api-app
    ports:
      - 5100:5000
    volumes:
      - ./API/app_code/.:/app
